create table person (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(50),
	gender VARCHAR(50) NOT NULL,
	date_of_birth DATE NOT NULL,
	country_of_birth VARCHAR(50)
);
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lorianna', 'Dmitrichenko', 'ldmitrichenko0@gov.uk', 'Female', '2022-08-21', 'United Kingdom');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Donavon', 'Nern', 'dnern1@biglobe.ne.jp', 'Male', '2023-06-24', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Boyd', 'McClymont', 'bmcclymont2@addthis.com', 'Male', '2023-01-02', 'Albania');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Esmaria', 'Cunnow', 'ecunnow3@earthlink.net', 'Agender', '2022-08-03', 'Bolivia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Blane', 'Yarnell', 'byarnell4@google.com.au', 'Male', '2023-03-29', 'Kazakhstan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Corbett', 'Wilson', 'cwilson5@hp.com', 'Male', '2023-04-15', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Horatia', 'Ollerhad', 'hollerhad6@nsw.gov.au', 'Female', '2023-06-12', 'Tajikistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Warde', 'Stoade', 'wstoade7@unc.edu', 'Non-binary', '2023-02-27', 'United States');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Immanuel', 'Checcucci', 'icheccucci8@nationalgeographic.com', 'Male', '2023-06-30', 'Sweden');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Malchy', 'Chansonne', 'mchansonne9@mac.com', 'Male', '2022-11-02', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Vanya', 'Knoller', 'vknollera@auda.org.au', 'Female', '2022-12-02', 'Venezuela');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Nils', 'Shoreson', 'nshoresonb@weebly.com', 'Male', '2022-07-29', 'Kazakhstan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Claus', 'Trower', 'ctrowerc@spiegel.de', 'Male', '2023-07-01', 'Greece');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Nicholas', 'Goodfellowe', 'ngoodfellowed@uol.com.br', 'Male', '2023-02-21', 'Albania');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Doralynn', 'Oulet', 'doulete@nasa.gov', 'Female', '2022-09-10', 'Argentina');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Moore', 'Hebborn', 'mhebbornf@un.org', 'Male', '2023-05-17', 'Netherlands');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Amanda', 'Power', 'apowerg@yellowbook.com', 'Female', '2022-10-04', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lusa', 'Lodemann', 'llodemannh@qq.com', 'Female', '2022-12-01', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Tracey', 'Fairbard', 'tfairbardi@home.pl', 'Female', '2022-09-24', 'Honduras');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Nevsa', 'Byre', 'nbyrej@abc.net.au', 'Female', '2022-09-07', 'Afghanistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Clemmie', 'Rowbotham', 'crowbothamk@theatlantic.com', 'Male', '2023-04-04', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Cyrill', 'Ielden', 'cieldenl@wufoo.com', 'Male', '2023-01-15', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Cort', 'Jouen', 'cjouenm@cdc.gov', 'Bigender', '2022-08-31', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Drew', 'Kaemena', 'dkaemenan@blinklist.com', 'Male', '2023-04-21', 'South Africa');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Boris', 'Balint', 'bbalinto@opensource.org', 'Male', '2023-04-23', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Bogey', 'Hobson', 'bhobsonp@stanford.edu', 'Male', '2022-07-31', 'Myanmar');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Halette', 'Chattaway', 'hchattawayq@npr.org', 'Female', '2022-10-18', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Madalena', 'Biggen', 'mbiggenr@state.tx.us', 'Female', '2022-10-16', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jon', 'Kettlewell', 'jkettlewells@theguardian.com', 'Polygender', '2022-10-31', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Greer', 'Rihosek', 'grihosekt@taobao.com', 'Female', '2023-01-19', 'Albania');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Korrie', 'Versey', 'kverseyu@cyberchimps.com', 'Female', '2023-05-26', 'United States');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Steffie', 'Leftley', 'sleftleyv@huffingtonpost.com', 'Female', '2022-09-30', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Luella', 'Boost', 'lboostw@cyberchimps.com', 'Female', '2023-02-08', 'Iran');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Cherilynn', 'Freear', 'cfreearx@va.gov', 'Female', '2023-02-20', 'Tanzania');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Egon', 'Stoate', 'estoatey@toplist.cz', 'Male', '2022-11-20', 'Venezuela');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Allys', 'Asch', 'aaschz@usa.gov', 'Female', '2023-01-25', 'Tajikistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Manda', 'Raiston', 'mraiston10@uol.com.br', 'Non-binary', '2023-03-03', 'Palestinian Territory');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Axe', 'Cogin', 'acogin11@cocolog-nifty.com', 'Male', '2022-09-06', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Darby', 'Scutter', 'dscutter12@nhs.uk', 'Agender', '2023-06-19', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Oby', 'Craw', 'ocraw13@globo.com', 'Male', '2022-10-25', 'Macedonia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Nickolaus', 'Pescott', 'npescott14@youtube.com', 'Male', '2023-01-27', 'Ukraine');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Conway', 'Fasham', 'cfasham15@squidoo.com', 'Male', '2023-07-05', 'Macedonia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Sterne', 'Downes', 'sdownes16@state.gov', 'Genderfluid', '2023-03-17', 'Pakistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Caro', 'Pimblett', 'cpimblett17@psu.edu', 'Female', '2022-12-10', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Selle', 'Malsher', 'smalsher18@joomla.org', 'Genderqueer', '2023-05-08', 'Djibouti');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Martica', 'Eacle', 'meacle19@exblog.jp', 'Female', '2022-12-23', 'Iran');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Kary', 'Worge', 'kworge1a@nbcnews.com', 'Female', '2023-05-25', 'Thailand');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Oneida', 'Burgin', 'oburgin1b@freewebs.com', 'Female', '2023-07-17', 'Uruguay');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jackson', 'Saffill', 'jsaffill1c@sogou.com', 'Male', '2023-05-08', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Gar', 'Mantle', 'gmantle1d@cargocollective.com', 'Male', '2022-09-15', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lola', 'Wretham', 'lwretham1e@google.ca', 'Female', '2022-10-19', 'Germany');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Inglebert', 'Seth', 'iseth1f@furl.net', 'Male', '2023-06-08', 'Czech Republic');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Ali', 'Bessey', 'abessey1g@upenn.edu', 'Male', '2022-11-10', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Kermy', 'Caccavella', 'kcaccavella1h@irs.gov', 'Male', '2022-08-04', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Quintilla', 'Hanretty', 'qhanretty1i@pbs.org', 'Female', '2023-03-14', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Zea', 'Bright', 'zbright1j@domainmarket.com', 'Female', '2022-11-07', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Arlie', 'Sandcraft', 'asandcraft1k@businesswire.com', 'Female', '2022-10-19', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Clerkclaude', 'Preece', 'cpreece1l@about.com', 'Male', '2022-07-21', 'Colombia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Cammy', 'Kunze', 'ckunze1m@slate.com', 'Female', '2022-08-04', 'South Africa');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Shurlocke', 'Scholey', 'sscholey1n@weather.com', 'Male', '2022-10-22', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Heath', 'Lockhart', 'hlockhart1o@theatlantic.com', 'Male', '2023-01-30', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Nahum', 'Clemmow', 'nclemmow1p@vimeo.com', 'Male', '2022-11-10', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Joey', 'Chasson', 'jchasson1q@addtoany.com', 'Female', '2023-02-03', 'Morocco');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Josee', 'Saphin', 'jsaphin1r@engadget.com', 'Female', '2022-12-27', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Rockwell', 'Pavel', 'rpavel1s@yale.edu', 'Male', '2022-11-13', 'Kyrgyzstan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Traver', 'Patnelli', 'tpatnelli1t@imdb.com', 'Male', '2022-07-31', 'Sri Lanka');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Friedrick', 'McArtan', 'fmcartan1u@craigslist.org', 'Male', '2023-04-12', 'Yemen');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Marabel', 'Jankiewicz', 'mjankiewicz1v@dagondesign.com', 'Female', '2023-02-04', 'United States');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Portie', 'Couroy', 'pcouroy1w@imdb.com', 'Male', '2022-12-22', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Joseito', 'Kitchin', 'jkitchin1x@angelfire.com', 'Male', '2023-02-22', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Flora', 'Negal', 'fnegal1y@hibu.com', 'Female', '2023-04-23', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Raffarty', 'Messier', 'rmessier1z@ca.gov', 'Genderfluid', '2023-04-23', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Franky', 'Ludwig', 'fludwig20@networkadvertising.org', 'Female', '2023-06-12', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Vaughn', 'Gobeaux', 'vgobeaux21@berkeley.edu', 'Male', '2023-06-14', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Pepita', 'Thurnham', 'pthurnham22@nhs.uk', 'Female', '2023-06-15', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Wood', 'Scaysbrook', 'wscaysbrook23@loc.gov', 'Male', '2023-04-16', 'Kyrgyzstan');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Nikolaus', 'Orrow', 'norrow24@163.com', 'Male', '2022-09-25', 'Chile');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Tate', 'Rayburn', 'trayburn25@freewebs.com', 'Female', '2022-07-20', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Erda', 'Cavalier', 'ecavalier26@alibaba.com', 'Female', '2023-03-02', 'Namibia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Uri', 'Mishaw', 'umishaw27@rediff.com', 'Male', '2022-10-03', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Garfield', 'Giraudo', 'ggiraudo28@nymag.com', 'Male', '2022-08-12', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Seward', 'Matis', 'smatis29@rambler.ru', 'Male', '2022-08-31', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Katerine', 'Nilges', 'knilges2a@bloomberg.com', 'Female', '2023-07-04', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Pat', 'Cheers', 'pcheers2b@unesco.org', 'Male', '2023-06-12', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Clark', 'Hackworthy', 'chackworthy2c@discovery.com', 'Male', '2022-08-06', 'Armenia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Thurstan', 'Horney', 'thorney2d@webs.com', 'Male', '2023-01-09', 'Myanmar');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Julius', 'De Cruze', 'jdecruze2e@imdb.com', 'Male', '2023-07-12', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Manya', 'Iseton', 'miseton2f@reuters.com', 'Female', '2023-03-28', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Lief', 'Nesbeth', 'lnesbeth2g@bigcartel.com', 'Male', '2023-06-26', 'Australia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Eleanore', 'Atmore', 'eatmore2h@a8.net', 'Female', '2023-03-31', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Fidel', 'Pimley', 'fpimley2i@deliciousdays.com', 'Male', '2022-11-03', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Ardene', 'Labes', 'alabes2j@a8.net', 'Female', '2023-06-06', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Nessy', 'Box', 'nbox2k@paypal.com', 'Female', '2022-10-22', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Perkin', 'Orsay', 'porsay2l@cdc.gov', 'Male', '2023-03-19', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Allys', 'Ralls', 'aralls2m@phoca.cz', 'Bigender', '2023-05-01', 'French Guiana');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Kizzie', 'Maasze', 'kmaasze2n@wordpress.com', 'Female', '2022-12-16', 'Mexico');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Fabien', 'Whear', 'fwhear2o@pbs.org', 'Male', '2022-08-06', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Maurie', 'Paddock', 'mpaddock2p@i2i.jp', 'Male', '2022-07-27', 'Czech Republic');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Selle', 'Andreini', 'sandreini2q@squarespace.com', 'Female', '2023-06-20', 'Vietnam');
insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Jodee', 'Hapke', 'jhapke2r@unc.edu', 'Genderqueer', '2022-10-23', 'China');
